import 'dotenv/config';
import path from 'node:path';

export const config = {
  nodeEnv: process.env.NODE_ENV ?? 'development',
  port: parseInt(process.env.PORT ?? '3000', 10),
  databaseUrl: process.env.DATABASE_URL ?? '',
  redisUrl: process.env.REDIS_URL ?? '',
  jwtSecret: process.env.JWT_SECRET ?? '',
  jwtRefreshSecret: process.env.JWT_REFRESH_SECRET ?? '',
  jwtExpiresIn: process.env.JWT_EXPIRES_IN ?? '15m',
  jwtRefreshExpiresIn: process.env.JWT_REFRESH_EXPIRES_IN ?? '7d',
  openaiApiKey: process.env.OPENAI_API_KEY ?? '',
  openaiModel: process.env.OPENAI_MODEL ?? 'gpt-4o-mini',
  openaiBaseUrl: process.env.OPENAI_BASE_URL ?? '',
  elevenLabsApiKey: process.env.ELEVENLABS_API_KEY ?? '',
  googleClientId: process.env.GOOGLE_CLIENT_ID ?? '',
  googleClientSecret: process.env.GOOGLE_CLIENT_SECRET ?? '',
  googleRedirectUri: process.env.GOOGLE_REDIRECT_URI ?? '',
  n8nBaseUrl: process.env.N8N_BASE_URL ?? '',
  n8nApiKey: process.env.N8N_API_KEY ?? '',
  browserEnabled: process.env.BROWSER_ENABLED !== 'false',
  browserHeadless: process.env.BROWSER_HEADLESS !== 'false',
  browserTimeout: parseInt(process.env.BROWSER_TIMEOUT ?? '30000', 10),
  browserIdleTimeoutMs: parseInt(process.env.BROWSER_IDLE_TIMEOUT_MS ?? '600000', 10),
  integrationRedirectBase:
    process.env.INTEGRATION_REDIRECT_BASE ?? 'http://localhost:3000/api/v1/integrations',
  integrationEncryptionKey: process.env.INTEGRATION_ENCRYPTION_KEY ?? '',
  githubClientId: process.env.GITHUB_CLIENT_ID ?? '',
  githubClientSecret: process.env.GITHUB_CLIENT_SECRET ?? '',
  slackClientId: process.env.SLACK_CLIENT_ID ?? '',
  slackClientSecret: process.env.SLACK_CLIENT_SECRET ?? '',
  discordWebhookEnabled: process.env.DISCORD_WEBHOOK_ENABLED ?? 'true',
  notionClientId: process.env.NOTION_CLIENT_ID ?? '',
  notionClientSecret: process.env.NOTION_CLIENT_SECRET ?? '',
  whatsappToken: process.env.WHATSAPP_TOKEN ?? '',
  whatsappPhoneNumberId: process.env.WHATSAPP_PHONE_NUMBER_ID ?? '',
  whatsappApiUrl: process.env.WHATSAPP_API_URL ?? 'https://graph.facebook.com/v18.0',
  corsOrigin: process.env.CORS_ORIGIN ?? 'http://localhost:3001',
  appVersion: '0.1.0',
  rateLimitMax: parseInt(process.env.RATE_LIMIT_MAX ?? '100', 10),
  rateLimitWindowMs: parseInt(process.env.RATE_LIMIT_WINDOW_MS ?? '60000', 10),
  logLevel: (process.env.LOG_LEVEL ?? 'info') as
    'trace' | 'debug' | 'info' | 'warn' | 'error' | 'fatal' | 'silent',
  pluginsDir: process.env.PLUGINS_DIR ?? path.join(process.cwd(), 'plugins'),
} as const;
